name: LOC Badge

on:
  schedule:
    - cron: "0 0 * * *"   # Run once per day (00:00 UTC)
  workflow_dispatch:       # Allow manual runs from the Actions tab

permissions:
  contents: write          # Required to push commits

jobs:
  loc-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Generate the original SVG badge
      - name: Generate LOC badge (SVG)
        id: badge
        uses: shadowmoose/GHA-LoC-Badge@1.0.0
        with:
          debug: false
          directory: ./               # Root of this repo (change if needed)
          badge: ./loc-badge.svg      # Output SVG file
          patterns: '*'               # File patterns (like .gitignore, separated by |)
          ignore: 'node_modules|.git|.github'

      # Install cloc + jq from apt (stable)
      - name: Install cloc & jq
        run: |
          sudo apt-get update
          sudo apt-get install -y cloc jq

      # Compute total LOC (number) and a human-friendly version
      - name: Compute LOC total
        id: loc
        shell: bash
        run: |
          set -e
          # cloc outputs JSON; take SUM.code
          TOTAL=$(cloc . --quiet --json --exclude-dir=.git,.github,node_modules | jq '.SUM.code // 0')
          HUMAN=$(numfmt --grouping "$TOTAL" 2>/dev/null || echo "$TOTAL")
          echo "total=$TOTAL" >> "$GITHUB_OUTPUT"
          echo "human=$HUMAN" >> "$GITHUB_OUTPUT"

      # Create Shields endpoint JSON with custom text
      - name: Build loc.json (Shields endpoint)
        env:
          HUMAN: ${{ steps.loc.outputs.human }}
        run: |
          printf '{\n' > loc.json
          printf '  "schemaVersion": 1,\n' >> loc.json
          printf '  "label": "From Hello World I'\''ve Written",\n' >> loc.json
          printf '  "message": "%s lines of code",\n' "$HUMAN" >> loc.json
          printf '  "color": "blue"\n' >> loc.json
          printf '}\n' >> loc.json

      # Commit both files (SVG + JSON) to gh-pages
      - name: Commit badge & JSON to gh-pages
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B gh-pages
          git add loc-badge.svg loc.json
          git commit -m "Update LOC badge & endpoint JSON" || echo "No changes"
          git push -f https://x-access-token:${TOKEN}@github.com/hajiabdolalireza/hajiabdolalireza.git gh-pages
