name: LOC Badge

on:
  schedule:
    - cron: "0 0 * * *"   # Run once per day
  workflow_dispatch:

jobs:
  loc-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate LOC badge (SVG)
        id: badge
        uses: shadowmoose/GHA-LoC-Badge@1.0.0
        with:
          debug: false
          directory: ./               # Root of this repo (you can change it)
          badge: ./loc-badge.svg      # Output SVG file
          patterns: '*'               # File patterns (like .gitignore, separated by |)
          ignore: 'node_modules|.git|.github'

      # Commit SVG file to gh-pages branch
      - name: Commit badge to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B gh-pages
          git add loc-badge.svg
          git commit -m "Update LOC badge" || echo "No changes"
          git push -f origin gh-pages
