name: Update README with recent activity

on:
  schedule:
    - cron: '*/30 * * * *'   
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Readme-Workflows/recent-activity@v2.4.1
        with:
          GH_TOKEN: ${{ secrets.RECENT_ACTIVITY_TOKEN }}
